### ISSUE TITLE
NServiceBus Router does not appear to survive MSMQ restarts

### ISSUE THREAD

**Issue by AJDray** [SzymonPobiega/NServiceBus.Router#45]
I have an NSB router responsible for Routing MSMQ messages to our Azure ServiceBus instance.

I have observed when I stop MSMQ and subsequently start it again the NServiceBus Router is unable to re-connect to the MSMQ instance.

```
System.Messaging.MessageQueueException (0x80004005): An invalid handle was passed to the function.
   at System.Messaging.MessageEnumerator.MoveNext(TimeSpan timeout)
   at NServiceBus.Transport.Msmq.MessagePump.<InnerProcessMessages>d__6.MoveNext()

```
Previous versions of the Router appeared to shut down the router. Whilst the latest version 3.9.2 appears to just continually poll MSMQ. 

Is there a way this could be reported as a critical error and then the service could be restarted?

**Comment by SzymonPobiega** [comment]
@AJDray I think this is actually a bug in the MSMQ transport itself. I'll verify that and keep you posted.

**Comment by SzymonPobiega** [comment]
I created an issue to track this https://github.com/Particular/NServiceBus.Transport.Msmq/issues/329
